stages:
    - deploy

variables:
  GIT_SSL_NO_VERIFY: "1"

pages:
  stage: deploy
  image: inseefrlab/onyxia-python-minimal
  script:
    - curl https://raw.githubusercontent.com/InseeFrLab/images-datascience/refs/heads/main/base/scripts/install-quarto.sh | sudo bash
    - mkdir -p public
    # - pip install uv
    # - uv sync
    - quarto render
    - mv _output public
    # - cat public/index.html
  artifacts:
    paths:
      - public
