project:
  title: "Présentation quarto-Insee"
lang: fr
editor: visual
slide-number: c/t
controls-layout: bottom-right
background-transition: fade
navigation-mode: vertical
transition-speed: slow
toc-title: Sommaire
toc-depth: 1
toc-float: true
number-sections: true
number-depth: 2
preview-links: true
code-fold: true
code-summary: "Code"
history: true
menu:
  side: left
  width: wide
width: 1920
height: 1080
header-includes: |
  <link rel="icon" type="image/png" sizes="32x32" href="img/logos/png/Logo_Insee_TailleMINI.jpg">
progress: true
include-after-body: ["modulesCompl/footer.html"]
theme: css/Insee_Commun.scss
css: [css/default.css]
revealjs-plugins:
  - pointer
  - confetti
  - verticator
filters:
  - roughnotation