project:
  title: "Présentation quarto-Insee"
  # output-dir: _output
  render:
    - "presentation-quarto.qmd"
    - "01_styleParDefaut.qmd"
    - "02_modulariteSupport.qmd"
    - "03_fenetreModale.qmd"
    - "04_exportPdf.qmd"
    - "05_documentation.qmd"
    
format:
  # choisissez le format : insee-vert-revealjs / insee-jaune-revealjs ou insee-rouge-revealjs
  insee-rouge-revealjs:
    # logo: img/logos/logoDeVotreService.png
    css: css/stylePerso.css
  odt: 
    prefer-html: true
    
header-includes: |
  <link rel="icon" type="image/png" sizes="32x32" href="img/logos/png/Logo_Insee_TailleMINI.jpg">
include-after-body: ["modulesCompl/footer.html"]

df-print: paged
lang: "fr"
slide-number: c/t
progress: true
controls-layout: bottom-right
background-transition: fade
navigation-mode: vertical
transition-speed: slow
number-sections: true
number-depth: 2
link-external-newwindow: true
# link-external-icon: true
code-fold: true
code-summary: "Code"
code-copy: true
highlight-style: atom-one
history: true
menu:
  side: left
  width: wide
width: 1920
height: 1080

theme: css/Insee_Commun.scss
css: [css/default.css, css/print.css]
revealjs-plugins:
  - pointer
  - confetti
  - verticator
filters:
  - roughnotation
embed-resources: true
