---
title: "Titre de la présentation"
subtitle: "Sous titre de la présentation"
date: today
date-format: "DD/MM/YYYY"
slide-tone: false # for blind readers
chalkboard: false # press the B key to toggle chalkboard
transition: slide # mots clés : none ; fade ; slide ; convex ; concave ; zoom
toc: true
# multiplex: true
format:
  # choisissez le format : insee-vert-revealjs / insee-jaune-revealjs ou insee-rouge-revealjs
  insee-rouge-revealjs:
    embed-resources: false
    # logo: img/logos/logoDeVotreService.png
    css: css/stylePerso.css
execute:
  echo: false
  warning: false
  cache: false
editor:
  render-on-save: true
---

# titre de niveau 1 {.backgroundTitre}

## Titre de niveau 2 {.backgroundStandard}

:::{.enteteAvecTitre}
titre de niveau 1
:::

### Titre de niveau 3

#### Titre de niveau 4

##### Titre de niveau 5

###### Titre de niveau 6

- liste de niveau 1
  - liste de niveau 2
    - liste de niveau 3
      - liste de niveau 4
        - liste de niveau 5
          - liste de niveau 6
          
## {#pageDeFin data-menu-title="Page finale" .unnumbered .backgroundPageFinale}

::: {.textPageFinale}
 Merci de votre attention
:::

::: {.textFooter}
Retrouvez nous sur
:::

:::: {.columns}

::: {.column .coordonnees width=50%}
- Prénom Nom
- fonction
- Service
- Numéro de téléphone
- Mél
:::

::: {.column .droite width=40%}
:::

::::

# Styles par défaut {.backgroundTitre}

## Style du texte {.backgroundStandard}

:::{.enteteAvecTitre}
Styles par défaut
:::

#### en markdown

*texte en italique* : `*texte en italique*`    
**texte en gras** : `**texte en gras**`    
***texte en gras et en italique*** : `***texte en gras et en italique***`   
~~texte barré~~ : `~~texte barré~~`

#### avec des balises html

<i>texte en italique</i> :  `<i>texte en italique</i>`   
<b>texte en gras</b> : `<b>texte en gras</b>`   
<strike>texte barré</strike> : `<strike>texte barré</strike>`  
<u>texte souligné</u> : `<u>texte souligné</u>`  
<br>
<i><u>exemple de balises combinées</i></u> :  `<i><u>exemple de balises combinées</i></u>`

## Style du texte {.backgroundStandard}

:::{.enteteAvecTitre}
Styles par défaut
:::

[gras]{.bold} : `[gras]{.bold}`&emsp;

[très gras]{.bolder} : `[très gras]{.bolder}`

### Taille des caractères

[Texte très petit]{.tiny} : `[Texte très petit]{.tiny}`  
[Texte plus petit]{.small} : `[Texte plus petit]{.small}`  
Texte standard : `Texte standard`  
[Texte plus grand]{.large} : `[Texte plus grand]{.large}`  
[Texte encore plus grand]{.Large} : `[Texte encore plus grand]{.Large}`  

- texte^[A footnote] : `texte^[A footnote]`
- texte<sub>a</sub> (indice) : `texte<sub>a</sub>`

## Couleurs du texte {.backgroundStandard}

:::{.enteteAvecTitre}
Styles par défaut
:::

[texte en noir]{.black} : `[texte en noir]{.black}`

[texte en rouge]{.red} : `[texte en rouge]{.red}`

[texte en bleu]{.blue} : `[texte en bleu]{.blue}`

[texte en vert]{.green} : `[texte en vert]{.green}`

[texte en jaune]{.yellow} : `[texte en jaune]{.yellow}`

[texte en orange]{.orange} : `[texte en orange]{.orange}`

[texte en violet]{.purple} : `[texte en violet]{.purple}`

[texte en gris]{.gray} : `[texte en gris]{.gray}` ou `[texte en gris]{.grey}`

[Texte en jaune Insee]{.jaune_insee} : `[Texte en jaune Insee].jaune_insee`

[Texte en rouge Insee]{.rouge_insee} : `[Texte en rouge Insee].rouge_insee`

[Texte en vert Insee]{.vert_insee} : `[Texte en vert Insee].vert_insee`

## Palette de couleurs de l'Insee {.backgroundStandard}

:::{.enteteAvecTitre}
Styles par défaut
:::

:::: columns
::: {.column width="45%" style="text-align: center;"}

#### Couleurs principales {style="margin: 5%; text-align: center;"}

[B6]{.nomPaletteCouleur .dot .B6}
[B5]{.nomPaletteCouleur .dot .B5}
[B4]{.nomPaletteCouleur .dot .B4}
[B3]{.nomPaletteCouleur .dot .B3}
[B2]{.nomPaletteCouleur .dot .B2}
[B1/2]{.nomPaletteCouleur .dot .B1demi}
[B1]{.nomPaletteCouleur .dot .B1}

[J6]{.nomPaletteCouleur .dot .J6}
[J5]{.nomPaletteCouleur .dot .J5}
[J4]{.nomPaletteCouleur .dot .J4}
[J3]{.nomPaletteCouleur .dot .J3}
[J2/3]{.nomPaletteCouleur .dot .J2tiers}
[J2]{.nomPaletteCouleur .dot .J2}
[J1]{.nomPaletteCouleur .dot .J1}

[G6]{.nomPaletteCouleur .dot .G6}
[G5]{.nomPaletteCouleur .dot .G5}
[G4]{.nomPaletteCouleur .dot .G4}
[G3]{.nomPaletteCouleur .dot .G3}
[G2]{.nomPaletteCouleur .dot .G2}
[G1/2]{.nomPaletteCouleur .dot .G1demi}
[G1]{.nomPaletteCouleur .dot .G1}

:::
::: {.column width="45%" style="text-align: center;"}

#### Couleurs complémentaires {style="margin: 5%; text-align: center;"}

[R5]{.nomPaletteCouleur .dot .R5}
[R4]{.nomPaletteCouleur .dot .R4}
[R3]{.nomPaletteCouleur .dot .R3}
[R2]{.nomPaletteCouleur .dot .R2}
[R1/2]{.nomPaletteCouleur .dot .R1demi}
[R1]{.nomPaletteCouleur .dot .R1}
[R0]{.nomPaletteCouleur .dot .R0}

[T5]{.nomPaletteCouleur .dot .T5}
[T4]{.nomPaletteCouleur .dot .T4}
[T3]{.nomPaletteCouleur .dot .T3}
[T2]{.nomPaletteCouleur .dot .T2}
[T1/2]{.nomPaletteCouleur .dot .T1demi}
[T1]{.nomPaletteCouleur .dot .T1}
[T0]{.nomPaletteCouleur .dot .T0}

[P5]{.nomPaletteCouleur .dot .P5}
[P4]{.nomPaletteCouleur .dot .P4}
[P3]{.nomPaletteCouleur .dot .P3}
[P2]{.nomPaletteCouleur .dot .P2}
[P1]{.nomPaletteCouleur .dot .P1}
[P1/0]{.nomPaletteCouleur .dot .Pdemi}
[P0]{.nomPaletteCouleur .dot .P0}

[V5]{.nomPaletteCouleur .dot .V5}
[V4]{.nomPaletteCouleur .dot .V4}
[V3]{.nomPaletteCouleur .dot .V3}
[V2]{.nomPaletteCouleur .dot .V2}
[V1]{.nomPaletteCouleur .dot .V1}
[V1/0]{.nomPaletteCouleur .dot .Vdemi}
[V0]{.nomPaletteCouleur .dot .V0}

:::
::::

[*Exemple :*]{.souligneRouge}

[texte non encadré de classe V5]{.V5} : `[texte non encadré de classe V5]{.V5}` 

## Content-box {.backgroundStandard}

:::{.enteteAvecTitre}
Styles par défaut
:::


[`[texte encadré sur fond jaune]{.content-box-yellow}`]{.tiny}

[texte encadré sur fond jaune]{.content-box-yellow}


[`[texte encadré sur fond rouge]{.content-box-red}`]{.tiny}

[texte encadré sur fond rouge]{.content-box-red}

[`[texte encadré sur fond vert]{.content-box-green}`]{.tiny}

[texte encadré sur fond vert]{.content-box-green}


[`[cadre en pleine largeur]{.full-width .content-box-yellow}`]{.tiny}

[cadre en pleine largeur]{.full-width .content-box-yellow}


## Content-box (sur 2 colonnes) {.backgroundStandard}

:::{.enteteAvecTitre}
Styles par défaut
:::

[[`[Très serré !...]{.pull-left-30}`]{.tiny}[Très serré !...]{.content-box-yellow .full-width}]{.pull-left-30}
[[`[Très au large !...]{.pull-right-70}`]{.tiny}[Très au large !...]{.content-box-yellow .full-width}]{.pull-right-70}

[[`[Serré !...]{.pull-left-40}`]{.tiny}[Serré !...]{.content-box-red .full-width}]{.pull-left-40}
[[`[Au large !...]{.pull-right-60}`]{.tiny}[Au large !...]{.content-box-red .full-width}]{.pull-right-60}

[[`[Moitié !...]{.pull-left-50}`]{.tiny}[Moitié !...]{.content-box-green .full-width}]{.pull-left-50}
[[`[Moitié !...]{.pull-right-50}`]{.tiny}[Moitié !...]{.content-box-green .full-width}]{.pull-right-50}

[[`[Au large !...]{.pull-left-60}`]{.tiny}[Au large !...]{.content-box-red .full-width}]{.pull-left-60}
[[`[Serré !...]{.pull-right-40}`]{.tiny}[Serré !...]{.content-box-red .full-width}]{.pull-right-40}

[[`[Très au large !...]{.pull-left-70}`]{.tiny}[Très au large !...]{.content-box-yellow .full-width}]{.pull-left-70}
[[`[Très serré !]{.pull-right-30}`]{.tiny}[Très serré !...]{.content-box-yellow .full-width}]{.pull-right-30}

## Equations mathématiques {.backgroundStandard}

:::{.enteteAvecTitre}
Styles par défaut
:::

#### Equation sur une ligne

```r
  $$TCAM=\sqrt[n]\frac{valeurfinale}{valeurinitiale}-1$$
```

$$TCAM=\sqrt[n]\frac{valeurfinale}{valeurinitiale}-1$$


#### Equation sur plusieurs lignes

:::{.pull-left-50}

```r
$$\begin{align}
(a+b)^3 &=(a+b)^2(a+b)\\
        &=(a^2+2ab+a^2)(a+b)\\
        &=a^3+3a^2b+3ab^2+b^3
\end{align}$$
```
:::
:::{{.pull-right-50}}

$$\begin{align}
(a+b)^3 &=(a+b)^2(a+b)\\
        &=(a^2+2ab+a^2)(a+b)\\
        &=a^3+3a^2b+3ab^2+b^3
\end{align}$$
:::


# documentation {.backgroundTitre}

## Sites de présentation {.backgroundStandard}

:::{.enteteAvecTitre}
documentation
:::

#### Quarto :

- [Présentation des fonctionnalités Quarto](https://quarto.org/docs/presentations/revealjs/demo/#/title-slide)
- [Code source associé à la présentation Quarto](https://github.com/quarto-dev/quarto-web/blob/main/docs/presentations/revealjs/demo/index.qmd)
- [quarto-tip_A_Day](https://mine-cetinkaya-rundel.github.io/quarto-tip-a-day/)

#### Insee :

- [charte graphique Insee](https://intranet.insee.fr/jcms/c_2182990/la-charte-graphique-editoriale)

## Technologies utilisées {.backgroundStandard}

:::{.enteteAvecTitre}
documentation
:::

- [documentation quarto](https://quarto.org/docs/presentations/)
- [documentation revealjs](https://revealjs.com/)
- [documentation scss](https://www.w3schools.com/sass/default.php)
- [documentation css](https://www.w3schools.com/css/default.asp)


## Extensions utilisées {.backgroundStandard}

:::{.enteteAvecTitre}
documentation
:::

- **Pointer :** presser "q" pour changer le pointer de la souris
- **Confetti :** presser "c" pour envoyer des confettis
- **Verticator :**
  - [exemple](https://martinomagnifico.github.io/reveal.js-verticator/demo.html#/)
  - [code de l'exemple](https://github.com/Martinomagnifico/quarto-verticator/blob/main/example.qmd)
- **roughtnotation :**
  - [exemple](https://emilhvitfeldt.github.io/quarto-roughnotation/#/title-slide) 
  - [code del'exemple](https://github.com/EmilHvitfeldt/quarto-roughnotation/blob/main/example.qmd)
- **fontawesome :**
  - [liste des icones](https://fontawesome.com/search?o=r&m=free)
    - [**Exemple :**]{.souligneRouge} {{< fa icons >}} (sans titre) ; {{< fa envelope title="Une envelope" >}} (avec titre)


# TITRE DE TROISIEME PARTIE QUI DOIT ÊTRE SUPER LONG POUR RENTRER SUR 2 LIGNES {.backgroundTitre}

## Sous-titre 3ème partie {.backgroundStandard}

:::{.enteteAvecTitre}
TITRE DE TROISIEME PARTIE QUI DOIT ÊTRE SUPER LONG POUR RENTRER SUR 2 LIGNES
:::

::: {.notes}
Speaker notes go here.
:::
